name: Go

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: false

      - name: lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest

  build:
    strategy:
      fail-fast: false
      matrix:
        go-versions: [1.16.x, 1.17.x, 1.18.x, 1.19.x, 1.20.x, 1.21.x, 1.22.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-versions }}
        cache: false

    - name: Run go test
      run: GO111MODULE=on go test -v -race ./...
